---
abstract: 'Perform XSLT transparently between XML::LibXSLT and Win32::MinXSLT'
author:
  - 'Klaus Eichner <klaus03@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141170'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-SList-XSLT
no_index:
  directory:
    - t
    - inc
requires:
  Win32::MinXSLT: '0.01'
resources:
  repository: https://github.com/klaus03/Acme-SList-XSLT.git
version: '0.02'
