---
abstract: 'Perform XSLT transparently between XML::LibXSLT and Win32::MinXSLT'
author:
  - 'Klaus Eichner <klaus03@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.3
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-SList-XSLT
provides:
  Acme::SList::XML:
    file: lib/Acme/SList/XSLT.pm
    version: 0
  Acme::SList::XSLT:
    file: lib/Acme/SList/XSLT.pm
    version: 0.01
requires:
  Win32::MinXSLT: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
